// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using LedgerMatch.Api;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LedgerMatch.Api.Migrations
{
    [DbContext(typeof(ReconciliationDb))]
    [Migration("20260924220304_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LedgerMatch.Api.Dataset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("LedgerMatch.Api.ReconciliationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeftDatasetId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("RightDatasetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RightDatasetId");

                    b.HasIndex("LeftDatasetId", "RightDatasetId")
                        .IsUnique();

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("LedgerMatch.Api.StoredRecord", b =>
                {
                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("DatasetId", "SourceRecordId");

                    b.HasIndex("DatasetId", "Reference", "Currency");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("LedgerMatch.Api.ReconciliationRun", b =>
                {
                    b.HasOne("LedgerMatch.Api.Dataset", null)
                        .WithMany()
                        .HasForeignKey("LeftDatasetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LedgerMatch.Api.Dataset", null)
                        .WithMany()
                        .HasForeignKey("RightDatasetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LedgerMatch.Api.StoredRecord", b =>
                {
                    b.HasOne("LedgerMatch.Api.Dataset", null)
                        .WithMany("Records")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LedgerMatch.Api.Dataset", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
